apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data-pvc
  namespace: kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-csi
